import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import StoreProvider from "@/components/StoreProvider";
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Challenge movies search',
  description: 'Generated by Lautaro Stein',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
